/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proj.projectui;

import com.proj.bean.EmpBean;
import com.proj.dao.EmpDao;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 91799
 */
public class AddEmployee1 extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee1() {
        initComponents();
    }
      public static void main(String[]args){
       JFrame jf= new JFrame ("Employee Form");
jf.setContentPane(new AddEmployee1());
jf.setBounds(100,200,600,700);
jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
jf.setVisible(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(java.awt.Color.blue);
        setForeground(java.awt.Color.blue);
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Employee Form");
        add(jLabel1);
        jLabel1.setBounds(110, 10, 150, 20);

        jLabel2.setText("Name");
        add(jLabel2);
        jLabel2.setBounds(40, 50, 32, 16);

        jLabel3.setText("Salary");
        add(jLabel3);
        jLabel3.setBounds(50, 80, 31, 16);

        jLabel4.setText("Deptno");
        add(jLabel4);
        jLabel4.setBounds(40, 110, 39, 16);

        jLabel5.setText("Comm");
        add(jLabel5);
        jLabel5.setBounds(40, 140, 37, 16);

        jLabel6.setText("Gender");
        add(jLabel6);
        jLabel6.setBounds(40, 170, 38, 16);

        jLabel7.setText("Empno");
        add(jLabel7);
        jLabel7.setBounds(40, 200, 38, 16);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abc(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(230, 230, 78, 33);
        add(jTextField1);
        jTextField1.setBounds(160, 40, 140, 30);
        add(jTextField2);
        jTextField2.setBounds(170, 80, 130, 20);
        add(jTextField3);
        jTextField3.setBounds(140, 100, 140, 30);
        add(jTextField4);
        jTextField4.setBounds(90, 130, 160, 22);
        add(jTextField5);
        jTextField5.setBounds(120, 200, 130, 20);

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        add(jComboBox1);
        jComboBox1.setBounds(120, 170, 101, 32);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abc(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(140, 230, 78, 33);

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abc(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(50, 230, 79, 33);
    }// </editor-fold>//GEN-END:initComponents

    private void abc(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abc
        // TODO add your handling code here:
        String opn=evt.getActionCommand();
      EmpDao ed= new EmpDao();
      EmpBean eb= new EmpBean();
      if(opn.equals("Delete")){
      int empno=Integer.parseInt(jTextField5.getText());
      int a=ed.deleteEmployee(empno);
      if(a>0){
      JOptionPane.showMessageDialog(this,"Employee Deleted Success");
      }
      else{
      JOptionPane.showMessageDialog(this,"Employee Not Deleted");
      }
    }//GEN-LAST:event_abc
else{
    String name=jTextField1.getText();
    float sal=Float.parseFloat(jTextField2.getText());
    int  deptno=Integer.parseInt(jTextField3.getText());
    float comm=Float.parseFloat(jTextField4.getText());
    String g=jComboBox1.getSelectedItem().toString();
    eb.setComm(comm);
    eb.setDeptno(deptno);
    eb.setGender(g);
    eb.setName(name);
    eb.setSal(sal);
    if(opn.equals("Save")){
    int a=ed.saveEmployee(eb);
    if(a>0){
         JOptionPane.showMessageDialog(this,"Employee Added Success");
    }
    else{
     JOptionPane.showMessageDialog(this,"Employee Not Added");
    }
    }
    else if(opn.equals("Update")){
    int empno=Integer.parseInt(jTextField5.getText());
    eb.setEmpno(empno);
    int y=ed.updateEmployee(eb);
    if(y>0){
         JOptionPane.showMessageDialog(this,"Employee Updated Success");
    }
    else{ JOptionPane.showMessageDialog(this,"Employee Added Success");
    }
    }
}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
