/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proj.projectui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JWindow;

/**
 *
 * @author 91799
 */
public class SplashPanel extends javax.swing.JPanel {

    /**
     * Creates new form SplashPanel
     */
    public SplashPanel() {
        initComponents();
    }
public void abc(int i){
jProgressBar1.setValue(i);
}
public static void main(String []args) throws InterruptedException {
Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
int x=(screen.width-428)/2;
int y=(screen.height-243)/2;
JWindow jw=new JWindow();
SplashPanel s= new SplashPanel();
jw.setContentPane(s);
jw.setBounds(x,y,428,243);
jw.setVisible(true);
for(int i=1;i<100;i++){    
        Thread.sleep(10);
  s.abc(i);
}
jw.setVisible(false);
JFrame jf= new JFrame("Login");
jf.setContentPane(new Login());
jf.pack();
jf.setLocationRelativeTo(null);
jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
jf.setVisible(true);

       
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new java.awt.BorderLayout());

        jProgressBar1.setBackground(new java.awt.Color(102, 102, 255));
        add(jProgressBar1, java.awt.BorderLayout.PAGE_END);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N
        jLabel2.setAlignmentX(2.0F);
        jLabel2.setAlignmentY(2.0F);
        add(jLabel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
